### ISSUE TITLE
Is 0.1.4 on npm?

### ISSUE THREAD

**Issue by siwel** [Bartvds/grunt-run-grunt#18]
When I install `grunt-run-grunt` with `grunt: 1.0.1`, then verify with `npm-ls` - It has an error of unmet peer dependency; 

`"peerDependencies": {    
    "grunt": "~0.4.1"     
  }`

Can the latest version be published to npm that has a grunt peer dependency of `>=0.4.0`

Thanks, Lewis

**Comment by killmenot** [comment]
@siwel please update to version 1.0.1 and let me know if you have any issues. Thanks
