### ISSUE TITLE
This tasks assumes global grunt install

### ISSUE THREAD

**Issue by iamchrismiller** [Bartvds/grunt-run-grunt#6]
When using this with an environment that doesn't install grunt globally but installs it locally, I.E. `./node_modules/.bin/grunt` the task breaks. 

What are your thoughts in making a simple check for local grunt and have the global a fallback?

```
var localBin = './node_modules/.bin/grunt';
var gruntBin fs.existsSync(localBin) ? localBin : 'grunt';
```

I can submit a pull request if this is something you want to add to your library.

**Comment by artemkaint** [comment]
+1

**Comment by artemkaint** [comment]
https://github.com/Bartvds/grunt-run-grunt/pull/11

**Comment by killmenot** [comment]
provided an options to specify custom path to grunt via https://github.com/Bartvds/grunt-run-grunt/commit/cfebaa7915ccb968293b5023755419117723241d
